version: '3.8'

services:
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile.server
    ports:
       - "${PORT:-5000}:${PORT:-5000}"
    env_file:
      - "./server/.env"
    depends_on:
      - mongo

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
